### ISSUE TITLE
Querying Contract Creation TX gives panic

### ISSUE THREAD

**Issue by joe-bowman** [CosmWasm/wasmd#102]
## Summary of Bug

Store erc20 contract in wasmd, then query the tx causes panic.

## Version
0.7.0 (xrncli/d 0.7.1)

## Steps to Reproduce

> wasmd tx wasm store <file.wasm> --from=<account>
TX hash returned
> wasmd q tx <TX>
 ### PANIC ###

```
Joes-MacBook-Pro:release joe$ xrncli q tx B3E40325A2BA91C1A17861DD8BF6849E69D8AC7952C82DB1B031415237FAA68D
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x491d035]

goroutine 1 [running]:
github.com/tendermint/tendermint/lite/proxy.GetCertifiedCommit(0xaf3d, 0x5009f40, 0xc000ead860, 0x0, 0x0, 0xc0000f2f20, 0x0, 0x0, 0x2)
	github.com/tendermint/tendermint@v0.33.0/lite/proxy/query.go:143 +0x105
github.com/cosmos/cosmos-sdk/client/context.CLIContext.Verify(0x0, 0x0, 0x0, 0x5009f40, 0xc000ead860, 0x0, 0x0, 0x0, 0x0, 0x4fd2940, ...)
	github.com/cosmos/cosmos-sdk@v0.38.1/client/context/query.go:116 +0x66
github.com/cosmos/cosmos-sdk/x/auth/client/utils.ValidateTxResult(0x0, 0x0, 0x0, 0x5009f40, 0xc000ead860, 0x0, 0x0, 0x0, 0x0, 0x4fd2940, ...)
	github.com/cosmos/cosmos-sdk@v0.38.1/x/auth/client/utils/query.go:128 +0x8e
github.com/cosmos/cosmos-sdk/x/auth/client/utils.QueryTx(0x0, 0x0, 0x0, 0x5009f40, 0xc000ead860, 0x0, 0x0, 0x0, 0x0, 0x4fd2940, ...)
	github.com/cosmos/cosmos-sdk@v0.38.1/x/auth/client/utils/query.go:93 +0x3bd
github.com/cosmos/cosmos-sdk/x/auth/client/cli.QueryTxCmd.func1(0xc000e6ef00, 0xc000ec2820, 0x1, 0x1, 0x0, 0x0)
	github.com/cosmos/cosmos-sdk@v0.38.1/x/auth/client/cli/query.go:165 +0x115
github.com/spf13/cobra.(*Command).execute(0xc000e6ef00, 0xc000ec27f0, 0x1, 0x1, 0xc000e6ef00, 0xc000ec27f0)
	github.com/spf13/cobra@v0.0.5/command.go:826 +0x460
github.com/spf13/cobra.(*Command).ExecuteC(0xc00011b900, 0x44907f0, 0xc00011b900, 0x4c8a7b2)
	github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v0.0.5/command.go:864
github.com/tendermint/tendermint/libs/cli.Executor.Execute(0xc00011b900, 0x4e890d0, 0x2, 0xc000e506c0)
	github.com/tendermint/tendermint@v0.33.0/libs/cli/setup.go:89 +0x3c
main.main()
	github.com/cosmwasm/wasmd@/cmd/xrncli/main.go:78 +0x5ab
```

Possibly a cosmos-sdk issue.
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by ethanfrey** [comment]
Seems like sdk. This has to do with getting proofs, right? I never tested this with proofs at all.

I'm closing this for now, but if you have a clear point where something is wrong with wasmd, please reopen (eg. We use the api wrong)
