### ISSUE TITLE
0.31.0-rc0 crashed in ibc-go when creating a channel

### ISSUE THREAD

**Issue by webmaster128** [CosmWasm/wasmd#1242]
I tried integrating a wasmd v0.31.0-rc0 based project and get a "invalid memory address or nil pointer dereference" crash when creating an IBC channel between two contracts:

```
 ✖ tests › set up channel Rejected promise returned by test
    ℹ Proxy port: wasm.wasm1qg5ega6dykkxc307y25pecuufrjkxkaggkkxh7nad0vhyhtuhw3sq29c3m
    ℹ Gateway port: wasm.nois1xxx3ps3gm3wceg4g300hvggdv7ga0hmsk64srccffmfy4wvcrugqmt97ya
  ─

  tests › set up channel
  Rejected promise returned by test. Reason:

  Error {
    message: `Query failed with (6): ␊
    github.com/cosmos/cosmos-sdk/baseapp.gRPCErrorToSDKError␊
        github.com/cosmos/cosmos-sdk@v0.45.14/baseapp/abci.go:627␊
    github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).handleQueryGRPC␊
        github.com/cosmos/cosmos-sdk@v0.45.14/baseapp/abci.go:603␊
    github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).Query␊
        github.com/cosmos/cosmos-sdk@v0.45.14/baseapp/abci.go:445␊
    github.com/tendermint/tendermint/abci/client.(*localClient).QuerySync␊
        github.com/tendermint/tendermint@v0.34.26/abci/client/local_client.go:256␊
    github.com/tendermint/tendermint/proxy.(*appConnQuery).QuerySync␊
        github.com/tendermint/tendermint@v0.34.26/proxy/app_conn.go:159␊
    github.com/tendermint/tendermint/rpc/core.ABCIQuery␊
        github.com/tendermint/tendermint@v0.34.26/rpc/core/abci.go:20␊
    reflect.Value.call␊
        reflect/value.go:586␊
    reflect.Value.Call␊
        reflect/value.go:370␊
    github.com/tendermint/tendermint/rpc/jsonrpc/server.makeJSONRPCHandler.func1␊
        github.com/tendermint/tendermint@v0.34.26/rpc/jsonrpc/server/http_json_handler.go:108␊
    github.com/tendermint/tendermint/rpc/jsonrpc/server.handleInvalidJSONRPCPaths.func1␊
        github.com/tendermint/tendermint@v0.34.26/rpc/jsonrpc/server/http_json_handler.go:140␊
    net/http.HandlerFunc.ServeHTTP␊
        net/http/server.go:2122␊
    net/http.(*ServeMux).ServeHTTP␊
        net/http/server.go:2500␊
    github.com/rs/cors.(*Cors).Handler.func1␊
        github.com/rs/cors@v1.8.2/cors.go:231␊
    net/http.HandlerFunc.ServeHTTP␊
        net/http/server.go:2122␊
    github.com/tendermint/tendermint/rpc/jsonrpc/server.maxBytesHandler.ServeHTTP␊
        github.com/tendermint/tendermint@v0.34.26/rpc/jsonrpc/server/http_server.go:256␊
    github.com/tendermint/tendermint/rpc/jsonrpc/server.RecoverAndLogHandler.func1␊
        github.com/tendermint/tendermint@v0.34.26/rpc/jsonrpc/server/http_server.go:229␊
    net/http.HandlerFunc.ServeHTTP␊
        net/http/server.go:2122␊
    net/http.serverHandler.ServeHTTP␊
        net/http/server.go:2936␊
    net/http.(*conn).serve␊
        net/http/server.go:1995␊
    rpc error: code = Unknown desc = recovered: runtime error: invalid memory address or nil pointer dereference␊
    stack:␊
    goroutine 79618 [running]:␊
    runtime/debug.Stack()␊
        runtime/debug/stack.go:24 +0x64␊
    github.com/cosmos/cosmos-sdk/baseapp.newDefaultRecoveryMiddleware.func1({0x1d9e900, 0x3936a40})␊
        github.com/cosmos/cosmos-sdk@v0.45.14/baseapp/recovery.go:71 +0x24␊
    github.com/cosmos/cosmos-sdk/baseapp.newRecoveryMiddleware.func1({0x1d9e900?, 0x3936a40?})␊
        github.com/cosmos/cosmos-sdk@v0.45.14/baseapp/recovery.go:39 +0x34␊
    github.com/cosmos/cosmos-sdk/baseapp.processRecovery({0x1d9e900, 0x3936a40}, 0x400000e258?)␊
        github.com/cosmos/cosmos-sdk@v0.45.14/baseapp/recovery.go:28 +0x38␊
    github.com/cosmos/cosmos-sdk/baseapp.processRecovery({0x1d9e900, 0x3936a40}, 0x29c86c8?)␊
        github.com/cosmos/cosmos-sdk@v0.45.14/baseapp/recovery.go:33 +0x60␊
    github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).runTx.func1()␊
        github.com/cosmos/cosmos-sdk@v0.45.14/baseapp/baseapp.go:632 +0xb4␊
    panic({0x1d9e900, 0x3936a40})␊
        runtime/panic.go:884 +0x1f4␊
    github.com/cosmos/ibc-go/v4/modules/core/05-port/types.(*Router).HasRoute(...)␊
        github.com/cosmos/ibc-go/v4@v4.3.0/modules/core/05-port/types/router.go:55␊
    github.com/cosmos/ibc-go/v4/modules/core/05-port/types.(*Router).GetRoute(...)␊
        github.com/cosmos/ibc-go/v4@v4.3.0/modules/core/05-port/types/router.go:61␊
    github.com/cosmos/ibc-go/v4/modules/core/keeper.Keeper.ChannelOpenTry({{0x0, 0x0}, {0x29c8c20, 0x400147ace0}, {{0x29a6730, 0x4000e5ac30}, {0x29c8c20, 0x400147ace0}, {{0x29c8c20, 0x400147ace0}, ...}, ...}, ...}, ...)␊
        github.com/cosmos/ibc-go/v4@v4.3.0/modules/core/keeper/msg_server.go:217 +0x130␊
    github.com/cosmos/ibc-go/v4/modules/core/04-channel/types._Msg_ChannelOpenTry_Handler.func1({0x29baf78, 0x40092710e0}, {0x1f535c0?, 0x4007365980})␊
        github.com/cosmos/ibc-go/v4@v4.3.0/modules/core/04-channel/types/tx.pb.go:1232 +0x74␊
    github.com/cosmos/cosmos-sdk/baseapp.(*MsgServiceRouter).RegisterService.func2.1({0x29baf78, 0x4009271080}, {0x400886c328?, 0xf79168?}, 0x1fdf540?, 0x4004f728a0)␊
        github.com/cosmos/cosmos-sdk@v0.45.14/baseapp/msg_service_router.go:113 +0x98␊
    github.com/cosmos/ibc-go/v4/modules/core/04-channel/types._Msg_ChannelOpenTry_Handler({0x1fd4b40?, 0x400149e280}, {0x29baf78, 0x4009271080}, 0x279d520, 0x4003a29da0)␊
        github.com/cosmos/ibc-go/v4@v4.3.0/modules/core/04-channel/types/tx.pb.go:1234 +0x12c␊
    github.com/cosmos/cosmos-sdk/baseapp.(*MsgServiceRouter).RegisterService.func2({{0x29baf08, 0x40001a6020}, {0x29c86c8, 0x4007402900}, {{0xb, 0x0}, {0x4001300449, 0x7}, 0x84f, {0x16a50114, ...}, ...}, ...}, ...)␊
        github.com/cosmos/cosmos-sdk@v0.45.14/baseapp/msg_service_router.go:126 +0x2e4␊
    github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).runMsgs(_, {{0x29baf08, 0x40001a6020}, {0x29c86c8, 0x4007402900}, {{0xb, 0x0}, {0x4001300449, 0x7}, 0x84f, ...}, ...}, ...)␊
        github.com/cosmos/cosmos-sdk@v0.45.14/baseapp/baseapp.go:760 +0x1f4␊
    github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).runTx(0x4000b00e00, 0x2, {0x4006b74900, 0x448, 0x480})␊
        github.com/cosmos/cosmos-sdk@v0.45.14/baseapp/baseapp.go:717 +0x980␊
    github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).Simulate(...)␊
        github.com/cosmos/cosmos-sdk@v0.45.14/baseapp/test_helpers.go:23␊
    github.com/cosmos/cosmos-sdk/x/auth/tx.txServer.Simulate({{{0x0, 0x0, 0x0}, {0x29d7e78, 0x4000b73a00}, {0x0, 0x0}, {0x29c0738, 0x400147ace0}, {0x29ce338, ...}, ...}, ...}, ...)␊
        github.com/cosmos/cosmos-sdk@v0.45.14/x/auth/tx/service.go:120 +0x10c␊
    github.com/cosmos/cosmos-sdk/types/tx._Service_Simulate_Handler({0x1efff20?, 0x40015564e0}, {0x29baf78, 0x400916dc80}, 0x40073182d0, 0x0)␊
        github.com/cosmos/cosmos-sdk@v0.45.14/types/tx/service.pb.go:910 +0x164␊
    github.com/cosmos/cosmos-sdk/baseapp.(*GRPCQueryRouter).RegisterService.func1({{0x29baf08, 0x40001a6020}, {0x29c86c8, 0x4007359800}, {{0xb, 0x0}, {0x4001300449, 0x7}, 0x84f, {0x16a50114, ...}, ...}, ...}, ...)␊
        github.com/cosmos/cosmos-sdk@v0.45.14/baseapp/grpcrouter.go:85 +0x188␊
    github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).handleQueryGRPC(0x4000b00e00, 0x4000b60900, {{0x4007353200, 0x44b, 0x900}, {0x4005244c90, 0x23}, 0x84f, 0x0})␊
        github.com/cosmos/cosmos-sdk@v0.45.14/baseapp/abci.go:601 +0x124␊
    github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).Query(0x4000b00e00, {{0x4007353200, 0x44b, 0x900}, {0x4005244c90, 0x23}, 0x84f, 0x0})␊
        github.com/cosmos/cosmos-sdk@v0.45.14/baseapp/abci.go:445 +0x6ec␊
    github.com/tendermint/tendermint/abci/client.(*localClient).QuerySync(0x4000ad35c0, {{0x4007353200, 0x44b, 0x900}, {0x4005244c90, 0x23}, 0x0, 0x0})␊
        github.com/tendermint/tendermint@v0.34.26/abci/client/local_client.go:256 +0x140␊
    github.com/tendermint/tendermint/proxy.(*appConnQuery).QuerySync(0x400441c200?, {{0x4007353200, 0x44b, 0x900}, {0x4005244c90, 0x23}, 0x0, 0x0})␊
        github.com/tendermint/tendermint@v0.34.26/proxy/app_conn.go:159 +0x5c␊
    github.com/tendermint/tendermint/rpc/core.ABCIQuery(0x8?, {0x4005244c90?, 0x4002e9ca80?}, {0x4007353200?, 0x4000f36ac8?, 0x4bdb58?}, 0x2?, 0x2?)␊
        github.com/tendermint/tendermint@v0.34.26/rpc/core/abci.go:20 +0x80␊
    reflect.Value.call({0x1dc5e80?, 0x279f958?, 0x4000e3f1e8?}, {0x1ff2920, 0x4}, {0x4006b7c800, 0x5, 0xd769dc?})␊
        reflect/value.go:586 +0x838␊
    reflect.Value.Call({0x1dc5e80?, 0x279f958?, 0x8dc?}, {0x4006b7c800?, 0x1feac60?, 0x4004d92145?})␊
        reflect/value.go:370 +0x90␊
    github.com/tendermint/tendermint/rpc/jsonrpc/server.makeJSONRPCHandler.func1({0x29b95f0, 0x400437fc68}, 0x4007262000)␊
        github.com/tendermint/tendermint@v0.34.26/rpc/jsonrpc/server/http_json_handler.go:108 +0xc38␊
    github.com/tendermint/tendermint/rpc/jsonrpc/server.handleInvalidJSONRPCPaths.func1({0x29b95f0?, 0x400437fc68?}, 0xffff5d1868f0?)␊
        github.com/tendermint/tendermint@v0.34.26/rpc/jsonrpc/server/http_json_handler.go:140 +0x70␊
    net/http.HandlerFunc.ServeHTTP(0x40034af7e8?, {0x29b95f0?, 0x400437fc68?}, 0x42b4ec?)␊
        net/http/server.go:2122 +0x38␊
    net/http.(*ServeMux).ServeHTTP(0x4000ac0240?, {0x29b95f0, 0x400437fc68}, 0x4007262000)␊
        net/http/server.go:2500 +0x13c␊
    github.com/rs/cors.(*Cors).Handler.func1({0x29b95f0, 0x400437fc68}, 0x4007262000)␊
        github.com/rs/cors@v1.8.2/cors.go:231 +0x1e4␊
    net/http.HandlerFunc.ServeHTTP(0x160?, {0x29b95f0?, 0x400437fc68?}, 0x0?)␊
        net/http/server.go:2122 +0x38␊
    github.com/tendermint/tendermint/rpc/jsonrpc/server.maxBytesHandler.ServeHTTP({{0x29a5540?, 0x4000b72c80?}, 0x10?}, {0x29b95f0?, 0x400437fc68}, 0x4007262000)␊
        github.com/tendermint/tendermint@v0.34.26/rpc/jsonrpc/server/http_server.go:256 +0x13c␊
    github.com/tendermint/tendermint/rpc/jsonrpc/server.RecoverAndLogHandler.func1({0x29b9c50?, 0x40062c90a0}, 0x4007262000)␊
        github.com/tendermint/tendermint@v0.34.26/rpc/jsonrpc/server/http_server.go:229 +0x2a8␊
    net/http.HandlerFunc.ServeHTTP(0x0?, {0x29b9c50?, 0x40062c90a0?}, 0x8d88a0?)␊
        net/http/server.go:2122 +0x38␊
    net/http.serverHandler.ServeHTTP({0x29a7a90?}, {0x29b9c50, 0x40062c90a0}, 0x4007262000)␊
        net/http/server.go:2936 +0x2c0␊
    net/http.(*conn).serve(0x4007260000, {0x29baf78, 0x40014ac7e0})␊
        net/http/server.go:1995 +0x518␊
    created by net/http.(*Server).Serve␊
        net/http/server.go:3089 +0x4e8␊
    : panic [cosmos/cosmos-sdk@v0.45.14/baseapp/recovery.go:69] With gas wanted: '50000000' and gas used: '55345' : unknown request`,
  }

  › : panic [cosmos/cosmos-sdk@v0.45.14/baseapp/recovery.go:69] With gas wanted: '50000000' and gas used: '55345' : unknown request
  › QueryClient.queryAbci (node_modules/@cosmjs/stargate/src/queryclient/queryclient.ts:645:13)
  › Object.request (node_modules/@cosmjs/stargate/src/queryclient/utils.ts:36:24)
  › Object.simulate (node_modules/@cosmjs/stargate/src/modules/tx/queries.ts:73:26)
  › SigningStargateClient.simulate (node_modules/@cosmjs/stargate/src/signingstargateclient.ts:175:25)
  › SigningStargateClient.signAndBroadcast (node_modules/@cosmjs/stargate/src/signingstargateclient.ts:289:29)
  › IbcClient.channelOpenTry (node_modules/@confio/relayer/src/lib/ibcclient.ts:1052:20)
  › Link.createChannel (node_modules/@confio/relayer/src/lib/link.ts:415:42)
```

The relevant lines in the stacktrace link to this code:
- https://github.com/cosmos/ibc-go/blob/v4.3.0/modules/core/05-port/types/router.go#L61
- https://github.com/cosmos/ibc-go/blob/v4.3.0/modules/core/05-port/types/router.go#L55

Any idea how this can lead to "invalid memory address or nil pointer dereference" and a panic?

**Comment by webmaster128** [comment]
This also happens when establishing an ICS-20 channel. So it might also be a bug in the node, not wasmd.

**Comment by webmaster128** [comment]
Closing for now as this is likely not a wasmd problem. Sorry for the noise.
