### ISSUE TITLE
Wasm response is not base64 encoded

### ISSUE THREAD

**Issue by Sirius198** [CosmWasm/wasmd#1315]
this is `go.mod` file
```
require (
	github.com/CosmWasm/wasmd v0.40.0-rc.0
	github.com/cometbft/cometbft v0.37.0
	github.com/cometbft/cometbft-db v0.7.0
	github.com/cosmos/cosmos-sdk v0.47.0
	github.com/cosmos/gogoproto v1.4.6
	github.com/cosmos/ibc-go/v7 v7.0.0
...
)
```

When uploading wasm file, i have this error.
```
/home/project-name/node_modules/base64-js/index.js:26
    throw new Error('Invalid string. Length must be a multiple of 4')
          ^

Error: Invalid string. Length must be a multiple of 4
    at getLens (/home/project-name/node_modules/base64-js/index.js:26:11)
    at Object.toByteArray (/home/project-name/node_modules/base64-js/index.js:55:14)
    at fromBase64 (/home/project-name/node_modules/@cosmjs/encoding/build/base64.js:36:21)
    at decodeAttribute (/home/project-name/node_modules/@cosmjs/tendermint-rpc/build/tendermint34/adaptor/responses.js:43:40)
    at Array.map (<anonymous>)
    at decodeAttributes (/home/project-name/node_modules/@cosmjs/tendermint-rpc/build/tendermint34/adaptor/responses.js:48:53)
    at decodeEvent (/home/project-name/node_modules/@cosmjs/tendermint-rpc/build/tendermint34/adaptor/responses.js:53:40)
    at Array.map (<anonymous>)
    at decodeEvents (/home/project-name/node_modules/@cosmjs/tendermint-rpc/build/tendermint34/adaptor/responses.js:58:49)
    at decodeTxData (/home/project-name/node_modules/@cosmjs/tendermint-rpc/build/tendermint34/adaptor/responses.js:66:31)
```

I got this logs from `/home/project-name/node_modules/@cosmjs/tendermint-rpc/build/tendermint34/adaptor/responses.js:L48`
by adding console.log
```
[
  {
    key: 'spender',
    value: '...',
    index: true
  },
  { key: 'amount', value: '10000000token', index: true }
]
```

response should be base64 encoded
```
[
  {
    key: 'c3BlbmRlcg==',
    value: '...',
    index: true
  },
  { key: 'YW1vdW50', value: 'MTAwMDAwMDB0b2tlbg==', index: true }
]
```

uploading frontend code works well with Cosmos SDK v0.45.11 and wasmd v0.29.2
so I think the bug is in blockchain app.

**Comment by Sirius198** [comment]
@EmilIvanichkovv 
how did you wire wasmd module into your app?

**Comment by EmilIvanichkovv** [comment]
as Buffer object

**Comment by EmilIvanichkovv** [comment]
@Sirius198 Can you clarify what you mean by "did you wire wasmd module"?

**Comment by Sirius198** [comment]
@EmilIvanichkovv 
I mean how did you add wasmd module in `app.go`.

**Comment by Sirius198** [comment]
did you use `main` branch? or which wasmd version did you use?

**Comment by EmilIvanichkovv** [comment]
version v0.40.0-rc.0

**Comment by alpe** [comment]
This is a change in the CometBFT (Tendermint) attribute key/ value types. They are [strings](https://github.com/cometbft/cometbft/blob/v0.37.0/proto/tendermint/abci/types.proto#L347-L348) and not [bytes](https://github.com/cometbft/cometbft/blob/v0.34.27/proto/tendermint/abci/types.proto#L323-L324) in CometBFT.
This can break clients but there is nothing we can do in wasmd.

**Comment by alpe** [comment]
Just got feedback from @webmaster128: 
You need to use a Tendermint 0.37 client instead of Tendermint 0.34 client 

Please see this [article](https://medium.com/cosmwasm/cosmjs-0-30-brings-telescope-types-and-a-tendermint-0-37-client-2a751381f44e) for more details.

You can get faster feedback on our [discord](https://chat.cosmwasm.com/).
