### ISSUE TITLE
Simulations fail sporadically

### ISSUE THREAD

**Issue by pinosu** [CosmWasm/wasmd#1437]
Logs from CI:
```
[W0] Spawned simulation with pid 98731 [seed=18931893 stdout=/tmp/sim-logs-1715377034/app-simulation-seed-18931893-date-06-06-2023_160434.stdout stderr=/tmp/sim-logs-1715377034/app-simulation-seed-18931893-date-06-06-2023_160434.stderr]
exit status 1
[W0] Seed 18931893: FAILED
To reproduce run: go test ./app -run TestAppStateDeterminism -Enabled=true -NumBlocks=1 -Genesis= -Verbose=true -Commit=true -Seed=18931893 -Period=1 -ExportParamsPath /tmp/sim-logs-1715377034/sim_params-18931893.json -ExportStatePath /tmp/sim-logs-1715377034/sim_state-18931893.json -v -timeout 24h
ERROR OUTPUT 

exit status 1
panic: halting simulations

goroutine 8 [running]:
main.worker(0x0?, 0x0?, 0x0?)
	/home/circleci/go/pkg/mod/github.com/cosmos/tools/cmd/runsim@v1.0.0/main.go:216 +0x629
main.main.func2(0x0?)
	/home/circleci/go/pkg/mod/github.com/cosmos/tools/cmd/runsim@v1.0.0/main.go:160 +0x5c
created by main.main
	/home/circleci/go/pkg/mod/github.com/cosmos/tools/cmd/runsim@v1.0.0/main.go:158 +0xdd0
make: *** [Makefile:153: test-sim-deterministic] Error 2

Exited with code exit status 2
```
See: https://app.circleci.com/pipelines/github/CosmWasm/wasmd/3651/workflows/6dcb95be-b290-4d90-ae48-dc4df56c5e6d/jobs/15444

**Comment by pinosu** [comment]
See also: https://app.circleci.com/pipelines/github/CosmWasm/wasmd/3653/workflows/9e9153bd-5342-4aa6-aa5b-9725b6ef5e8d/jobs/15456

**Comment by pinosu** [comment]
There is a bug in sdk simulations. See https://github.com/cosmos/cosmos-sdk/issues/16525
