### ISSUE TITLE
panic: proto: could not resolve import

### ISSUE THREAD

**Issue by gupadhyaya** [CosmWasm/wasmd#1785]
```
panic: proto: could not resolve import "core/crypto/pb/crypto.proto": not found

goroutine 1 [running]:
github.com/CosmWasm/wasmd/app.NewWasmApp({0x1043356d0, 0x106611700}, {0x104355010, 0x14001188b80}, {0x0, 0x0}, 0x0, {0x1042f1f78, 0x140008a2150}, {0x1400141eb00, ...}, ...)
	github.com/CosmWasm/wasmd/app/app.go:903 +0x7378
main.NewRootCmd()
	github.com/CosmWasm/wasmd/cmd/wasmd/root.go:40 +0x504
main.main()
	github.com/CosmWasm/wasmd/cmd/wasmd/main.go:14 +0x1c
```

commenting out https://github.com/CosmWasm/wasmd/blob/main/app/app.go#L902-L904 works fine. 

Steps to reproduce:
* `go mod replace github.com/cosmos/cosmos-sdk => github.com/rollkit/cosmos-sdk v0.50.1-rollkit-v0.11.19-no-fraud-proofs`
* `github.com/rollkit/cosmos-sdk` uses `github.com/rollkit/rollkit`, which in turn uses `go-libp2p`  which looks like having the `core/crypto/pb/crypto.proto` that is not found above.
* `wasmd start --rollkit.aggregator true --rollkit.da_start_height $DA_BLOCK_HEIGHT --minimum-gas-prices="0.025stake"` throws the error above

**Comment by bap2pecs** [comment]
we also met w the same issue and we are commenting out the code as a tmp fix as well

```
	protoFiles, err := proto.MergedRegistry()
	// if err != nil {
	// 	panic(err)
	// }
```

but we want to know:

- if there is any plan to fix it
- what's the implication of this tmp fix b/c we are concerned that adding this check might have some reasons

**Comment by lesterli** [comment]
Fixed this panic issue by upgrading the `cosmos/gogoproto` version to `v1.5.0`.
