### ISSUE TITLE
Can't restart with cosmos-sdk 0.38

### ISSUE THREAD

**Issue by ethanfrey** [cosmwasm/wasmd#54]
## Summary of Bug

I start a single node. Create one sendtx. Restart the node and it dies with a consensus failure.

This only happened after the 0.38 upgrade. Thank you to @litvintech for reporting this to me (from another v0.38.0 binary)

## Version

master branch, `697a286` and `3de4ee6` have both been shown with the issue.

## Steps to Reproduce

Setup and start node:

```
rm -rf ~/.wasmd
make install

wasmcli keys add validator
wasmcli keys add fred

wasmd init --chain-id=testing testing
wasmd add-genesis-account $(wasmcli keys show validator -a) 1000000000stake,1000000000validatortoken
wasmd gentx --name validator
wasmd collect-gentxs
wasmd start
```

Make a sendtx (in another terminal)

```
wasmcli tx send $(wasmcli keys show validator -a) $(wasmcli keys show fred -a) 98765stake -y
```

Then, kill the `wasmd` node, and start it up again.

#### Output

```
E[2020-01-27|12:20:13.030] CONSENSUS FAILURE!!!                         module=consensus err="stored minter should not have been nil" stack="goroutine 130 [running]:\nruntime/debug.Stack(0xc000da1460, 0x1114340, 0x1667790)\n\truntime/debug/stack.go:24 +0x9d\ngithub.com/tendermint/tendermint/consensus.(*State).receiveRoutine.func2(0xc000c7c700, 0x149a170)\n\tgithub.com/tendermint/tendermint@v0.33.0/consensus/state.go:613 +0x57\npanic(0x1114340, 0x1667790)\n\truntime/panic.go:679 +0x1b2\ngithub.com/cosmos/cosmos-sdk/x/mint/internal/keeper.Keeper.GetMinter(0xc000105880, 0x169cc00, 0xc00030f7e0, 0xc000105880, 0x169cc00, 0xc00030f820, 0x169cc40, 0xc00030f870, 0xc000e9be00, 0x4, ...)\n\tgithub.com/cosmos/cosmos-sdk@v0.38.0/x/mint/internal/keeper/keeper.go:57 +0x18f\ngithub.com/cosmos/cosmos-sdk/x/mint.BeginBlocker(0x16ad500, 0xc00003e120, 0x16c1bc0, 0xc000d962c0, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0, ...)\n\tgithub.com/cosmos/cosmos-sdk@v0.38.0/x/mint/abci.go:11 +0x8e\ngithub.com/cosmos/cosmos-sdk/x/mint.AppModule.BeginBlock(...)\n\tgithub.com/cosmos/cosmos-sdk@v0.38.0/x/mint/module.go:130\ngithub.com/cosmos/cosmos-sdk/types/module.(*Manager).BeginBlock(0xc00011b650, 0x16ad500, 0xc00003e120, 0x16c1bc0, 0xc000d962c0, 0xa, 0x0, 0x0, 0x0, 0x0, ...)\n\tgithub.com/cosmos/cosmos-sdk@v0.38.0/types/module/module.go:297 +0x1ca\ngithub.com/cosmwasm/wasmd/app.(*WasmApp).BeginBlocker(...)\n\tgithub.com/cosmwasm/wasmd@/app/app.go:332\ngithub.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).BeginBlock(0xc000e0b7c0, 0xc000dff5e0, 0x20, 0x20, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0, ...)\n\tgithub.com/cosmos/cosmos-sdk@v0.38.0/baseapp/abci.go:136 +0x469\ngithub.com/tendermint/tendermint/abci/client.(*localClient).BeginBlockSync(0xc000c1d680, 0xc000dff5e0, 0x20, 0x20, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0, ...)\n\tgithub.com/tendermint/tendermint@v0.33.0/abci/client/local_client.go:231 +0x101\ngithub.com/tendermint/tendermint/proxy.(*appConnConsensus).BeginBlockSync(0xc000c26c50, 0xc000dff5e0, 0x20, 0x20, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0, ...)\n\tgithub.com/tendermint/tendermint@v0.33.0/proxy/app_conn.go:69 +0x6b\ngithub.com/tendermint/tendermint/state.execBlockOnProxyApp(0x16adf00, 0xc000afc5e0, 0x16bb0a0, 0xc000c26c50, 0xc000c52c40, 0x16c3bc0, 0xc000b6c090, 0x6, 0xc000e9c560, 0x7)\n\tgithub.com/tendermint/tendermint@v0.33.0/state/execution.go:280 +0x3e1\ngithub.com/tendermint/tendermint/state.(*BlockExecutor).ApplyBlock(0xc000337ea0, 0xa, 0x0, 0xc000e9c550, 0x6, 0xc000e9c560, 0x7, 0x6, 0xc00030a2c0, 0x20, ...)\n\tgithub.com/tendermint/tendermint@v0.33.0/state/execution.go:131 +0x17a\ngithub.com/tendermint/tendermint/consensus.(*State).finalizeCommit(0xc000c7c700, 0x7)\n\tgithub.com/tendermint/tendermint@v0.33.0/consensus/state.go:1431 +0x8f5\ngithub.com/tendermint/tendermint/consensus.(*State).tryFinalizeCommit(0xc000c7c700, 0x7)\n\tgithub.com/tendermint/tendermint@v0.33.0/consensus/state.go:1350 +0x383\ngithub.com/tendermint/tendermint/consensus.(*State).enterCommit.func1(0xc000c7c700, 0x0, 0x7)\n\tgithub.com/tendermint/tendermint@v0.33.0/consensus/state.go:1285 +0x90\ngithub.com/tendermint/tendermint/consensus.(*State).enterCommit(0xc000c7c700, 0x7, 0x0)\n\tgithub.com/tendermint/tendermint@v0.33.0/consensus/state.go:1322 +0x61a\ngithub.com/tendermint/tendermint/consensus.(*State).addVote(0xc000c7c700, 0xc0001368c0, 0x0, 0x0, 0xc000d6fac0, 0x434c31, 0x149b450)\n\tgithub.com/tendermint/tendermint@v0.33.0/consensus/state.go:1819 +0xa39\ngithub.com/tendermint/tendermint/consensus.(*State).tryAddVote(0xc000c7c700, 0xc0001368c0, 0x0, 0x0, 0x8, 0xc000d6fad0, 0x4bc07d)\n\tgithub.com/tendermint/tendermint@v0.33.0/consensus/state.go:1642 +0x59\ngithub.com/tendermint/tendermint/consensus.(*State).handleMsg(0xc000c7c700, 0x168b280, 0xc000b6c1e0, 0x0, 0x0)\n\tgithub.com/tendermint/tendermint@v0.33.0/consensus/state.go:709 +0x252\ngithub.com/tendermint/tendermint/consensus.(*State).receiveRoutine(0xc000c7c700, 0x0)\n\tgithub.com/tendermint/tendermint@v0.33.0/consensus/state.go:660 +0x579\ncreated by github.com/tendermint/tendermint/consensus.(*State).OnStart\n\tgithub.com/tendermint/tendermint@v0.33.0/consensus/state.go:335 +0x13a\n"
^CE[2020-01-27|12:20:14.898] Not stopping BlockPool -- have not been started yet module=blockchain impl=BlockPool
E[2020-01-27|12:20:14.898] Stopped accept routine, as transport is closed module=p2p numPeers=0
```

Expanding the stacktrace (printing the string, not just \n):

```
goroutine 130 [running]:
runtime/debug.Stack(0xc000da1460, 0x1114340, 0x1667790)
	runtime/debug/stack.go:24 +0x9d
github.com/tendermint/tendermint/consensus.(*State).receiveRoutine.func2(0xc000c7c700, 0x149a170)
	github.com/tendermint/tendermint@v0.33.0/consensus/state.go:613 +0x57
panic(0x1114340, 0x1667790)
	runtime/panic.go:679 +0x1b2
github.com/cosmos/cosmos-sdk/x/mint/internal/keeper.Keeper.GetMinter(0xc000105880, 0x169cc00, 0xc00030f7e0, 0xc000105880, 0x169cc00, 0xc00030f820, 0x169cc40, 0xc00030f870, 0xc000e9be00, 0x4, ...)
	github.com/cosmos/cosmos-sdk@v0.38.0/x/mint/internal/keeper/keeper.go:57 +0x18f
github.com/cosmos/cosmos-sdk/x/mint.BeginBlocker(0x16ad500, 0xc00003e120, 0x16c1bc0, 0xc000d962c0, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	github.com/cosmos/cosmos-sdk@v0.38.0/x/mint/abci.go:11 +0x8e
github.com/cosmos/cosmos-sdk/x/mint.AppModule.BeginBlock(...)
	github.com/cosmos/cosmos-sdk@v0.38.0/x/mint/module.go:130
github.com/cosmos/cosmos-sdk/types/module.(*Manager).BeginBlock(0xc00011b650, 0x16ad500, 0xc00003e120, 0x16c1bc0, 0xc000d962c0, 0xa, 0x0, 0x0, 0x0, 0x0, ...)
	github.com/cosmos/cosmos-sdk@v0.38.0/types/module/module.go:297 +0x1ca
github.com/cosmwasm/wasmd/app.(*WasmApp).BeginBlocker(...)
	github.com/cosmwasm/wasmd@/app/app.go:332
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).BeginBlock(0xc000e0b7c0, 0xc000dff5e0, 0x20, 0x20, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	github.com/cosmos/cosmos-sdk@v0.38.0/baseapp/abci.go:136 +0x469
github.com/tendermint/tendermint/abci/client.(*localClient).BeginBlockSync(0xc000c1d680, 0xc000dff5e0, 0x20, 0x20, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	github.com/tendermint/tendermint@v0.33.0/abci/client/local_client.go:231 +0x101
github.com/tendermint/tendermint/proxy.(*appConnConsensus).BeginBlockSync(0xc000c26c50, 0xc000dff5e0, 0x20, 0x20, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	github.com/tendermint/tendermint@v0.33.0/proxy/app_conn.go:69 +0x6b
github.com/tendermint/tendermint/state.execBlockOnProxyApp(0x16adf00, 0xc000afc5e0, 0x16bb0a0, 0xc000c26c50, 0xc000c52c40, 0x16c3bc0, 0xc000b6c090, 0x6, 0xc000e9c560, 0x7)
	github.com/tendermint/tendermint@v0.33.0/state/execution.go:280 +0x3e1
github.com/tendermint/tendermint/state.(*BlockExecutor).ApplyBlock(0xc000337ea0, 0xa, 0x0, 0xc000e9c550, 0x6, 0xc000e9c560, 0x7, 0x6, 0xc00030a2c0, 0x20, ...)
	github.com/tendermint/tendermint@v0.33.0/state/execution.go:131 +0x17a
github.com/tendermint/tendermint/consensus.(*State).finalizeCommit(0xc000c7c700, 0x7)
	github.com/tendermint/tendermint@v0.33.0/consensus/state.go:1431 +0x8f5
github.com/tendermint/tendermint/consensus.(*State).tryFinalizeCommit(0xc000c7c700, 0x7)
	github.com/tendermint/tendermint@v0.33.0/consensus/state.go:1350 +0x383
github.com/tendermint/tendermint/consensus.(*State).enterCommit.func1(0xc000c7c700, 0x0, 0x7)
	github.com/tendermint/tendermint@v0.33.0/consensus/state.go:1285 +0x90
github.com/tendermint/tendermint/consensus.(*State).enterCommit(0xc000c7c700, 0x7, 0x0)
	github.com/tendermint/tendermint@v0.33.0/consensus/state.go:1322 +0x61a
github.com/tendermint/tendermint/consensus.(*State).addVote(0xc000c7c700, 0xc0001368c0, 0x0, 0x0, 0xc000d6fac0, 0x434c31, 0x149b450)
	github.com/tendermint/tendermint@v0.33.0/consensus/state.go:1819 +0xa39
github.com/tendermint/tendermint/consensus.(*State).tryAddVote(0xc000c7c700, 0xc0001368c0, 0x0, 0x0, 0x8, 0xc000d6fad0, 0x4bc07d)
	github.com/tendermint/tendermint@v0.33.0/consensus/state.go:1642 +0x59
github.com/tendermint/tendermint/consensus.(*State).handleMsg(0xc000c7c700, 0x168b280, 0xc000b6c1e0, 0x0, 0x0)
	github.com/tendermint/tendermint@v0.33.0/consensus/state.go:709 +0x252
github.com/tendermint/tendermint/consensus.(*State).receiveRoutine(0xc000c7c700, 0x0)
	github.com/tendermint/tendermint@v0.33.0/consensus/state.go:660 +0x579
created by github.com/tendermint/tendermint/consensus.(*State).OnStart
	github.com/tendermint/tendermint@v0.33.0/consensus/state.go:335 +0x13a
```
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by ethanfrey** [comment]
Some investigation:

1. The `GetMinter` that failed, relies on `SetMinter` having previously been called: [link](https://github.com/cosmos/cosmos-sdk/blob/master/x/mint/internal/keeper/keeper.go#L52-L70).
2. `SetMinter` is called in `BeginBlock`: [link](https://github.com/cosmos/cosmos-sdk/blob/master/x/mint/abci.go#L19-L20)
3. As well as `InitGenesis`: [link](https://github.com/cosmos/cosmos-sdk/blob/master/x/mint/genesis.go#L9-L10)

Thinking that maybe we hadn't properly registered the links, I checked `app.go` and found:

1. `Minter` is registered in `SetOrderInitGenesis`: [link](https://github.com/cosmwasm/wasmd/blob/master/app/app.go#L281-L286)
2. `Minter` is registered in `SetOrderBeginBlockers`: [link](https://github.com/cosmwasm/wasmd/blob/master/app/app.go#L276-L277) In fact it is exactly in this `BeginBlock` call that the panic occurs.

Very odd...

**Comment by ethanfrey** [comment]
Adding some debug into into `Get/SetMinter` in the cosmos-sdk and then re-running gives this:

```
wasmd start
I[2020-01-27|12:54:42.638] starting ABCI with Tendermint                module=main 
SetMinter: types.Minter{Inflation:0.130000000000000000, AnnualProvisions:0.000000000000000000}
  StoreKey: KVStoreKey{0xc000bc54d0, mint}
GetMinter: types.Minter{Inflation:0.130000000000000000, AnnualProvisions:0.000000000000000000}
  StoreKey: KVStoreKey{0xc000bc54d0, mint}
SetMinter: types.Minter{Inflation:0.130000017523039605, AnnualProvisions:130000017.523039605000000000}
  StoreKey: KVStoreKey{0xc000bc54d0, mint}
I[2020-01-27|12:54:47.710] Executed block                               module=state height=1 validTxs=0 invalidTxs=0
I[2020-01-27|12:54:47.712] Committed state                              module=state height=1 txs=0 appHash=E7034D34D9122D5B6F5386275EC877BA605DCB735324300FED3D36CBED334954
GetMinter: types.Minter{Inflation:0.130000017523039605, AnnualProvisions:130000017.523039605000000000}
  StoreKey: KVStoreKey{0xc000bc54d0, mint}
SetMinter: types.Minter{Inflation:0.130000035046079271, AnnualProvisions:130000037.646079971921585420}
  StoreKey: KVStoreKey{0xc000bc54d0, mint}
I[2020-01-27|12:54:52.739] Executed block                               module=state height=2 validTxs=0 invalidTxs=0
I[2020-01-27|12:54:52.743] Committed state                              module=state height=2 txs=0 appHash=FBB9F9198A465EBD2E9DCE3E3C6D97F940F863A2F7FEE8B6A7CCA916DE47254E
GetMinter: types.Minter{Inflation:0.130000035046079271, AnnualProvisions:130000037.646079971921585420}
  StoreKey: KVStoreKey{0xc000bc54d0, mint}
SetMinter: types.Minter{Inflation:0.130000052569118999, AnnualProvisions:130000057.769121101764759960}
  StoreKey: KVStoreKey{0xc000bc54d0, mint}
I[2020-01-27|12:54:57.770] Executed block                               module=state height=3 validTxs=0 invalidTxs=0
```

Looking fine, but then in restart:

```
I[2020-01-27|12:57:21.200] starting ABCI with Tendermint                module=main 
  StoreKey: KVStoreKey{0xc000b73460, mint}
panic: stored minter should not have been nil
...
```

**Comment by ethanfrey** [comment]
The only thing I can think of that would cause this is if `fauxMerkleMode` was enabled, or if we use a memdb backing store.

`sim_test.go` does enable this fauxMerkleMode: [link](https://github.com/cosmwasm/wasmd/blob/master/app/sim_test.go#L41-L46), but I don't see it anywhere in non-test code.

And when I print out the db used in `newApp`, I get: `Using DB: &db.GoLevelDB{db:(*leveldb.DB)(0xc000090540)}`

Notably, the leveldb stored on disk is very small. I know there is only one account, but all the other info (like staking, minter, etc) should take up some space.

```
$ ls -l ~/.wasmd/data/application.db/
total 20
-rw-r--r-- 1 ethan ethan 1118 Jan 27 12:55 000002.ldb
-rw-r--r-- 1 ethan ethan    0 Jan 27 13:05 000009.log
-rw-r--r-- 1 ethan ethan   16 Jan 27 13:05 CURRENT
-rw-r--r-- 1 ethan ethan   16 Jan 27 13:05 CURRENT.bak
-rw-r--r-- 1 ethan ethan    0 Jan 27 12:54 LOCK
-rw-r--r-- 1 ethan ethan 2491 Jan 27 13:05 LOG
-rw-r--r-- 1 ethan ethan   75 Jan 27 13:05 MANIFEST-000010
```

**Comment by ethanfrey** [comment]
If I run for 50 blocks, I notice the application db gets much larger:

```
$ ls -l ~/.wasmd/data/application.db/
total 44
-rw-r--r-- 1 ethan ethan 24923 Jan 27 13:14 000001.log
-rw-r--r-- 1 ethan ethan    16 Jan 27 13:10 CURRENT
-rw-r--r-- 1 ethan ethan     0 Jan 27 13:10 LOCK
-rw-r--r-- 1 ethan ethan   359 Jan 27 13:10 LOG
-rw-r--r-- 1 ethan ethan    54 Jan 27 13:10 MANIFEST-000000
```

And on restart it does some compaction:

```
$ ls -l ~/.wasmd/data/application.db/
total 32
-rw-r--r-- 1 ethan ethan 14640 Jan 27 13:15 000002.ldb
-rw-r--r-- 1 ethan ethan     0 Jan 27 13:15 000003.log
-rw-r--r-- 1 ethan ethan    16 Jan 27 13:15 CURRENT
-rw-r--r-- 1 ethan ethan    16 Jan 27 13:15 CURRENT.bak
-rw-r--r-- 1 ethan ethan     0 Jan 27 13:10 LOCK
-rw-r--r-- 1 ethan ethan   947 Jan 27 13:15 LOG
-rw-r--r-- 1 ethan ethan   109 Jan 27 13:15 MANIFEST-000004
```

The LOG file (after restart) reads like:

```
=============== Jan 27, 2020 (CET) ===============
13:10:47.542640 log@legend F·NumFile S·FileSize N·Entry C·BadEntry B·BadBlock Ke·KeyError D·DroppedEntry L·Level Q·SeqNum T·TimeElapsed
13:10:47.552682 db@open opening
13:10:47.554062 version@stat F·[] S·0B[] Sc·[]
13:10:47.556412 db@janitor F·2 G·0
13:10:47.556480 db@open done T·3.751612ms
=============== Jan 27, 2020 (CET) ===============
13:15:24.477013 log@legend F·NumFile S·FileSize N·Entry C·BadEntry B·BadBlock Ke·KeyError D·DroppedEntry L·Level Q·SeqNum T·TimeElapsed
13:15:24.477099 version@stat F·[] S·0B[] Sc·[]
13:15:24.477113 db@open opening
13:15:24.477141 journal@recovery F·1
13:15:24.477450 journal@recovery recovering @1
13:15:24.486149 memdb@flush created L0@2 N·100 S·14KiB "s/1,v1":"s/latest,v2"
13:15:24.486559 version@stat F·[1] S·14KiB[14KiB] Sc·[0.25]
13:15:24.491663 db@janitor F·3 G·0
13:15:24.491685 db@open done T·14.565404ms
```

I am getting the feel that the new iavl tree is not writing everything to disk

**Comment by ethanfrey** [comment]
Digging into iavl:

I see an odd memdb [leaking in here](https://github.com/tendermint/iavl/blob/be60f693315ce981e1c8458881387644dd417d18/mutable_tree.go#L27-L31)

`snapDB` is the actual `GoLevelDB` store, and `recentDB` is just `MemDB` on [this line](https://github.com/tendermint/iavl/blob/be60f693315ce981e1c8458881387644dd417d18/mutable_tree.go#L55): `ndb := newNodeDB(snapDB, recentDB, cacheSize, opts)`

**Comment by ethanfrey** [comment]
Digging into the usage:

`LoadStore` [passes in the pruning options](https://github.com/cosmos/cosmos-sdk/blob/master/store/iavl/store.go#L39-L45), which are `PruneNothing` [by default](https://github.com/cosmos/cosmos-sdk/blob/master/store/rootmulti/store.go#L55). Which again has [`keepEvery` as 1](https://github.com/cosmos/cosmos-sdk/blob/master/store/types/pruning.go#L32), which does seem right

**Comment by ethanfrey** [comment]
It seems a workaround would be to add this to `app.toml`

```toml
pruning = "nothing"
```

And, testing, this did produce functional code.

However, the other (default) settings should not produce unusable nodes

**Comment by litvintech** [comment]
@ethanfrey great and fast research!

Found the same thing couple of minutes ago when I tried to play with pruning options passing them to

**Comment by zmanian** [comment]
The expected behavior is that on a clean shutdown, the latest state should be persisted to disk.

The state should also be reconstructed by Tendermint replaying txs over ABCI

**Comment by ethanfrey** [comment]
Yes, but if the genesis/init state is never written, this is a major issue.

**Comment by ethanfrey** [comment]
If nothing else, you should always flush block 1 to disk

**Comment by ethanfrey** [comment]
Update: I did try flushing block 1 to disk with a small patch to iavl

```go
func (ndb *nodeDB) isSnapshotVersion(version int64) bool {
	return version == 1 || (ndb.opts.KeepEvery != 0 && version%ndb.opts.KeepEvery == 0)
}
```

Result:

```
$ wasmd start
I[2020-01-27|14:30:17.230] starting ABCI with Tendermint                module=main 
I[2020-01-27|14:30:22.317] Executed block                               module=state height=1 validTxs=0 invalidTxs=0
I[2020-01-27|14:30:22.319] Committed state                              module=state height=1 txs=0 appHash=79E4391F796A1B0DA9B99C285ECCA78FDDF5D0C75B3217064003A40618284EBB
I[2020-01-27|14:30:27.345] Executed block                               module=state height=2 validTxs=0 invalidTxs=0
I[2020-01-27|14:30:27.349] Committed state                              module=state height=2 txs=0 appHash=8ECBCF1C775A8BA907C38543F58B0CFD5F7E363557783297F584B69DC08F6F08
I[2020-01-27|14:30:32.374] Executed block                               module=state height=3 validTxs=0 invalidTxs=0
I[2020-01-27|14:30:32.378] Committed state                              module=state height=3 txs=0 appHash=CD6A8CE1880851CE54B7B08139332A338CF103AAB431ABF06787FBDBB30E76AB
I[2020-01-27|14:30:37.400] Executed block                               module=state height=4 validTxs=0 invalidTxs=0
I[2020-01-27|14:30:37.403] Committed state                              module=state height=4 txs=0 appHash=4DD6C6504F81B36E657F905A126CB5652FA97A6B554EBCDD5A0BEDC4DD2C6CD1
E[2020-01-27|14:30:41.384] Not stopping BlockPool -- have not been started yet module=blockchain impl=BlockPool
I[2020-01-27|14:30:41.385] exiting...                                   module=main 
E[2020-01-27|14:30:41.385] Stopped accept routine, as transport is closed module=p2p numPeers=0

$ wasmd start
I[2020-01-27|14:30:42.344] starting ABCI with Tendermint                module=main 
failed to load Store: wanted to load target 4 but only found up to 1
```

So... cosmos-sdk is writing the CommitInfo to disk every block (containing the last version of all the sub-iavl stores). And when those are not written, it cannot load them.

**Comment by ethanfrey** [comment]
Another demo, hardcoding opts.KeepEvery to 5 in iavl

```go
```

Restarting after exactly a multiple of 5 blocks works:

```
$ wasmd start
I[2020-01-27|14:35:26.036] starting ABCI with Tendermint                module=main 
I[2020-01-27|14:35:31.110] Executed block                               module=state height=1 validTxs=0 invalidTxs=0
I[2020-01-27|14:35:31.114] Committed state                              module=state height=1 txs=0 appHash=966F157225821E06F58BA5739DEEE085B886D47EC1CE4EF3FCBEA0FEB5AD8991
I[2020-01-27|14:35:36.136] Executed block                               module=state height=2 validTxs=0 invalidTxs=0
I[2020-01-27|14:35:36.140] Committed state                              module=state height=2 txs=0 appHash=E3A3B76227EA3DCDE32E148F766B397775856B8B952DDE7334AB958F7E9085EC
I[2020-01-27|14:35:41.168] Executed block                               module=state height=3 validTxs=0 invalidTxs=0
I[2020-01-27|14:35:41.171] Committed state                              module=state height=3 txs=0 appHash=7C9543DCCF7AB01D8491A7385B22C631DBE89448BF66157CF04D2BC406E5D371
I[2020-01-27|14:35:46.193] Executed block                               module=state height=4 validTxs=0 invalidTxs=0
I[2020-01-27|14:35:46.197] Committed state                              module=state height=4 txs=0 appHash=443859BE994AE69FB78D1EE95E7E04E41DB7A8BE740C052F67B7EE88DED116C1
I[2020-01-27|14:35:51.223] Executed block                               module=state height=5 validTxs=0 invalidTxs=0
I[2020-01-27|14:35:51.227] Committed state                              module=state height=5 txs=0 appHash=43B031EEB594F082BFB3E3BA6CCBEF7228F0B640FEFD4A6F8EDD3D6E0B3CAF6B
E[2020-01-27|14:35:52.221] Not stopping BlockPool -- have not been started yet module=blockchain impl=BlockPool
E[2020-01-27|14:35:52.221] Stopped accept routine, as transport is closed module=p2p numPeers=0
I[2020-01-27|14:35:52.221] exiting...                                   module=main 

$ wasmd start
I[2020-01-27|14:35:54.693] starting ABCI with Tendermint                module=main 
I[2020-01-27|14:35:59.853] Executed block                               module=state height=6 validTxs=0 invalidTxs=0
I[2020-01-27|14:35:59.858] Committed state                              module=state height=6 txs=0 appHash=BE2A1621E1281761CBAB5E286761B484EBAFDED8932B3367C0D26E1C61D03DBD
```

But stopping a bit later and restarting doens't:

```
I[2020-01-27|14:36:04.874] Executed block                               module=state height=7 validTxs=0 invalidTxs=0
I[2020-01-27|14:36:04.877] Committed state                              module=state height=7 txs=0 appHash=162F9F4429578920F083C5830D8E87A84ACC9E1B8B89B22F7E23E0CD7921AF9E
E[2020-01-27|14:36:05.407] Not stopping BlockPool -- have not been started yet module=blockchain impl=BlockPool
I[2020-01-27|14:36:05.415] exiting...                                   module=main 
E[2020-01-27|14:36:05.415] Stopped accept routine, as transport is closed module=p2p numPeers=0

$ wasmd start
I[2020-01-27|14:36:06.961] starting ABCI with Tendermint                module=main 
failed to load Store: wanted to load target 7 but only found up to 5
```

it is quite apparent now that the KeepEvery logic in iavl doesn't play well together with RootMultistore. And needs a larger refactor of cosmos-sdk/store

**Comment by zmanian** [comment]
The expectation is the CommitInfo should only contain the last persisted block.
