### ISSUE TITLE
Integrate wasm to cosmos-sdk failed.

### ISSUE THREAD

**Issue by bruce-wayne2** [CosmWasm/wasmd#852]
I tried to integrate v0.27.0-rc0 into our project, and imported the nameservice contract according to the documentation, and successfully executed a series of query and tx commands. But when I try to stop the chain (via starport), the chain crashes, below is part of the error stack:

```
[STARPORT] 💿 Saving genesis state...
panic: Error calling the VM: Cache error: Error opening Wasm file for reading: No such file or directory (os error 2)

goroutine 1 [running]:
chain/x/wasm/keeper.ExportGenesis.func1(0x1, {{0x140016f07e0, 0x20, 0x20}, {0x14001522960, 0x2a}, {0x3, {0x0, 0x0}}})
        /path/to/chain/x/wasm/keeper/genesis.go:93 +0x264
chain/x/wasm/keeper.Keeper.IterateCodeInfos({{0x102c9e648, 0x14001690500}, {0x102cc7030, 0x140011d98f0}, {0x102cb5788, 0x140000ef200}, {0x102c9c5b8, 0x140016911d0}, {0x102c984b8, 0x140000310f8}, ...}, ...)
        /path/to/chain/x/wasm/keeper/keeper.go:741 +0x1f8
chain/x/wasm/keeper.ExportGenesis({{0x102cb6670, 0x1400005a0c8}, {0x102cc5718, 0x140016932c0}, {{0x0, 0x0}, {0x0, 0x0}, 0x338, {0x0, ...}, ...}, ...}, ...)
        /path/to/chain/x/wasm/keeper/genesis.go:90 +0x1dc
chain/x/wasm.AppModule.ExportGenesis({{}, {_, _}, _, {_, _}, {_, _}, {_, _}}, ...)
        /path/to/chain/x/wasm/module.go:172 +0x84
github.com/cosmos/cosmos-sdk/types/module.(*Manager).ExportGenesis(_, {{0x102cb6670, 0x1400005a0c8}, {0x102cc5718, 0x140016932c0}, {{0x0, 0x0}, {0x0, 0x0}, 0x338, ...}, ...}, ...)

```

```go
// ExportGenesis returns a GenesisState for a given context and keeper.
func ExportGenesis(ctx sdk.Context, keeper *Keeper) *types.GenesisState {
	var genState types.GenesisState

	genState.Params = keeper.GetParams(ctx)

	keeper.IterateCodeInfos(ctx, func(codeID uint64, info types.CodeInfo) bool {
		bytecode, err := keeper.GetByteCode(ctx, codeID)
		if err != nil {
			panic(err)
		}
		genState.Codes = append(genState.Codes, types.Code{
			CodeID:    codeID,
			CodeInfo:  info,
			CodeBytes: bytecode,
			Pinned:    keeper.IsPinnedCode(ctx, codeID),
		})
		return false
	})

	keeper.IterateContractInfo(ctx, func(addr sdk.AccAddress, contract types.ContractInfo) bool {
		var state []types.Model
		keeper.IterateContractState(ctx, addr, func(key, value []byte) bool {
			state = append(state, types.Model{Key: key, Value: value})
			return false
		})
		// redact contract info
		contract.Created = nil
		genState.Contracts = append(genState.Contracts, types.Contract{
			ContractAddress: addr.String(),
			ContractInfo:    contract,
			ContractState:   state,
		})
		return false
	})

	for _, k := range [][]byte{types.KeyLastCodeID, types.KeyLastInstanceID} {
		genState.Sequences = append(genState.Sequences, types.Sequence{
			IDKey: k,
			Value: keeper.PeekAutoIncrementID(ctx, k),
		})
	}

	return &genState
}
```

Device: Macbook pro  M1

**Comment by ethanfrey** [comment]
We do not support starport. And last I heard they don't support CosmWasm integration anymore.

This has to do with not providing proper directory to store the wasm files. Please check with the starport team about adding better support

**Comment by bruce-wayne2** [comment]
> We do not support starport. And last I heard they don't support CosmWasm integration anymore.
> 
> This has to do with not providing proper directory to store the wasm files. Please check with the starport team about adding better support

Sorry, I may not have been clear. I am referring to `wasmd`, the manually integrated `CosmWasm`.


Below is my code to create `Wasm` keeper:
```go
	wasmDir := filepath.Join(homePath, "wasm")
	wasmConfig, err := wasm.ReadWasmConfig(appOpts)
	if err != nil {
		panic(fmt.Sprintf("error while reading wasm config: %s", err))
	}
	// The last arguments can contain custom message handlers, and custom query handlers,
	// if we want to allow any custom callbacks
	supportedFeatures := "iterator,staking,stargate"
	app.wasmKeeper = wasm.NewKeeper(
		appCodec,
		keys[wasm.StoreKey],
		app.GetSubspace(wasm.ModuleName),
		app.AccountKeeper,
		app.BankKeeper,
		app.StakingKeeper,
		app.DistrKeeper,
		app.IBCKeeper.ChannelKeeper,
		&app.IBCKeeper.PortKeeper,
		scopedWasmKeeper,
		app.TransferKeeper,
		app.MsgServiceRouter(),
		app.GRPCQueryRouter(),
		wasmDir,
		wasmConfig,
		supportedFeatures,
		wasmOpts...,
	)
```

**Comment by ethanfrey** [comment]
I know. `starport chain serve -r` is odd, does things with state we don't normally do, and doesn't support CosmWasm last I heard.

If you have trouble running normal wasmd commands, we would be more likely to help (and link your entire app.go). But it is a known issue that starport doesn't play well with x/wasm

**Comment by bruce-wayne2** [comment]
Thanks for your answer, I will try it later without using `starport`.

**Comment by bruce-wayne2** [comment]
I no longer encounter this problem after I no longer use `starport`.
