### ISSUE TITLE
Wasm contract missing a required marker export: interface_version_*: create wasm contract failed

### ISSUE THREAD

**Issue by Abhishek-1857** [CosmWasm/wasmd#884]
Error when broadcasting tx 2ED56F1D69BEBEDB2B5FEC49F0C2D02F0634399AEC2563DFED9F2CD1A98A7D0E at height 416914. Code: 2; Raw log: failed to execute message; message index: 0: Error calling the VM: Error during static Wasm validation: Wasm contract missing a required marker export: interface_version_*: create wasm contract failed
    at SigningCosmWasmClient.upload (/home/user/gxt-bridge/cw-examples/node_modules/@cosmjs/cosmwasm-stargate/build/signingcosmwasmclient.js:82:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async main (/home/user/gxt-bridge/cw-examples/newCont.js:37:27)

**Comment by alpe** [comment]
Closing this now
